#!/bin/bash

repo_dir="$(cd "$(dirname "$0")"; pwd)"

progress() { echo ==== "$@" ; }

if [ ! -f "$repo_dir/ext/maude" ]; then
    mkdir -p "$repo_dir/ext"

    progress "Fetching Maude"
    curl -o "$repo_dir/ext/maude.tar.bz2" "https://courses.engr.illinois.edu/cs576/fa2019/tools/maude-a120-mac.tar.bz2"
    (cd $repo_dir/ext && tar -xzf maude.tar.bz2 && rm maude.tar.bz2)
fi

if [ ! -f "$repo_dir/ext/rltool" ]; then
    mkdir -p "$repo_dir/ext"

    progress "Fetching RL Tool"
    curl -o "$repo_dir/ext/rltool.tar.bz2" "https://courses.engr.illinois.edu/cs576/fa2019/tools/rltool.tar.bz2"
    (cd $repo_dir/ext && tar -xzf rltool.tar.bz2 && rm rltool.tar.bz2 && rm -f "$repo_dir/ext/rltool/meta-aux.maude" && cp "$repo_dir/meta-aux.maude" "$repo_dir/ext/rltool/")
fi
