#!/bin/bash

repo_dir="$(cd "$(dirname "$0")"; pwd)"

progress() { echo ==== "$@" ; }

if [ ! -f "$repo_dir/ext/maude" ]; then
    mkdir -p "$repo_dir/ext"

    progress "Fetching Maude"
    curl -o "$repo_dir/ext/maude.tar.bz2" "https://courses.engr.illinois.edu/cs576/fa2019/tools/maude-a120-mac.tar.bz2"
    (cd $repo_dir/ext && tar -xzf maude.tar.bz2 && rm maude.tar.bz2)
fi
