#!/bin/bash

repo_dir="$(cd "$(dirname "$0")"; pwd)"

maude_binary="$repo_dir/ext/maude-a120/maude"

if [ ! -f $maude_binary ]; then
    echo "[Warning]: Need to \"build\" first" >&2
    "$repo_dir/build"
fi

$maude_binary $@
